provider:
  aws:
    profile_name: ebdev
    secret_key: null
    access_key: null
    

project:
  name: rxtb-test
  sync:
    exclude:
      - .git/*
      - __*__.py
    include:
      - rixtribute/example-gpu.DockerFile
      - rixtribute/example-gpu.DockerFile

container:
  - name: pytorch-training
    file: rixtribute/example-gpu.DockerFile
    ports: [5000]

instance:
  - name: gpu-iptc
    provider: aws
    container: pytorch-training
    config: 
      region: eu-west-1a
      type: p3.2xlarge
      keyname: jesper_ssh
      ami: ami-0e032abfb10b0b80a
      spot: true
      ports: ["tcp:22"]
      volumes:
        - devname: /dev/xvda
          size: 50
  - name: test-iptc
    provider: aws
    config: 
      region: eu-west-1a
      type: m5.large
      keyname: jesper_ssh
      ami: ami-0e032abfb10b0b80a
      spot: true
      volumes:
        - devname: /dev/xvda
          size: 100
