provider:
  aws:
    profile_name: ebdev
    secret_key: null
    access_key: null
    

project:
  name: rxtb-test
  sync:
    exclude:
      - .git/*
      - __*__.py
    include:
      - rixtribute/example-gpu.DockerFile
      - rixtribute/example-gpu.DockerFile

container:
  - name: pytorch-training
    path: .
    file: rixtribute/example-gpu.DockerFile
    ports:
      - containerPort: 5000
        hostPort: 5000
  - name: nginx-test
    path: .
    file: rixtribute/example-nginx.DockerFile
    ports:
      - containerPort: 80
        hostPort: 8080

instance:
  - name: gpu-iptc
    provider: aws
    container: pytorch-training
    config: 
      region: eu-west-1a
      type: p3.2xlarge
      keyname: jesper_ssh
      ami: ami-0e032abfb10b0b80a
      spot: true
      ports: ["tcp:22"]
      volumes:
        - devname: /dev/xvda
          size: 50
  - name: amazon-linux-2-dlami
    provider: aws
    container: pytorch-training
    config: 
      region: eu-west-1a
      type: p2.xlarge
      ami: ami-037ae87a2e8684759
      spot: true
      volumes:
        - devname: /dev/xvda
          size: 100
  - name: test-nginx
    provider: aws
    container: nginx-test
    config: 
      region: eu-west-1a
      type: m5.large
      ami: ami-037ae87a2e8684759
      spot: true
      ports: ["tcp:22", "tcp:80"]
      volumes:
        - devname: /dev/xvda
          size: 100
  - name: test-iptc
    provider: aws
    container: pytorch-training
    config: 
      region: eu-west-1a
      type: m5.large
      keyname: jesper_ssh
      ami: ami-0e032abfb10b0b80a
      spot: true
      volumes:
        - devname: /dev/xvda
          size: 100

commands:
    train: |
        [[ -e /.dockerenv ]] && echo "inside docker"
        for (( i = 0; i < 3; i++ )); do
          echo "training epoch #$i"
          sleep 1
        done
        echo "finished training.."
    tensorboard: |
        tensorboard --bind_all --port 6006 --logdir /workspace/project/training

